FROM tiangolo/uvicorn-gunicorn-starlette:python3.8

ENV JOB_CONFIG_PATH=/app/job/config.json

COPY ./jnjjobwrapper /lib/jnjjobwrapper

RUN pip install /lib/jnjjobwrapper

COPY ./jnjhttpjob/jnjhttpjob /app/

